extends: substitution
message: "Use '%s' instead of '%s'"
level: error
action:
  name: replace
swap:
  data store: database
  thru: through
  admin: administrator
  util: utility
  info: information
  config: configuration
  dev: development
  prod: production
  env: environment
  repo: repository
  auth: authentication
  sec: security
  perf: performance
  opt: optimization
  impl: implementation
  ref: reference
  doc: documentation
  api: API
  ui: UI
  ux: UX
  css: CSS
  html: HTML
  js: JavaScript
  ts: TypeScript
  json: JSON
  yaml: YAML
  xml: XML
  sql: SQL
  nosql: NoSQL
  saas: SaaS
  paas: PaaS
  iaas: IaaS
  ci: CI
  cd: CD
  cicd: CI/CD
  devops: DevOps
  devex: DevEx
  dxi: DXI
  wcag: WCAG
  gdpr: GDPR
  ccpa: CCPA
  soc2: SOC 2
  iso27001: ISO 27001
  nist: NIST
  owasp: OWASP
  rls: RLS
  rbac: RBAC
  oauth: OAuth
  pkce: PKCE
  jwt: JWT
  ssl: SSL
  tls: TLS
  http: HTTP
  https: HTTPS
  rest: REST
  graphql: GraphQL
  rpc: RPC
  grpc: gRPC
  tcp: TCP
  udp: UDP
  dns: DNS
  cdn: CDN
  dsl: DSL
  ide: IDE
  cli: CLI
  gui: GUI
  tui: TUI
  cpu: CPU
  gpu: GPU
  ram: RAM
  ssd: SSD
  hdd: HDD
  vm: VM
  container: container
  kubernetes: Kubernetes
  docker: Docker
  k8s: Kubernetes
  iac: IaC
  git: Git
  github: GitHub
  gitlab: GitLab
  bitbucket: Bitbucket
  jenkins: Jenkins
  travis: Travis CI
  circleci: CircleCI
  vercel: Vercel
  heroku: Heroku
  aws: AWS
  azure: Azure
  gcp: GCP
  firebase: Firebase
  supabase: Supabase
  stripe: Stripe
  paypal: PayPal
  square: Square
  plaid: Plaid
  twilio: Twilio
  sendgrid: SendGrid
  mailgun: Mailgun
  ses: SES
  sns: SNS
  sqs: SQS
  lambda: Lambda
  cloudfront: CloudFront
  s3: S3
  ec2: EC2
  rds: RDS
  dynamodb: DynamoDB
  redis: Redis
  postgresql: PostgreSQL
  mysql: MySQL
  mongodb: MongoDB
  cassandra: Cassandra
  elasticsearch: Elasticsearch
  solr: Solr
  lucene: Lucene
  react: React
  vue: Vue
  angular: Angular
  svelte: Svelte
  nextjs: Next.js
  nuxt: Nuxt
  gatsby: Gatsby
  remix: Remix
  astro: Astro
  vite: Vite
  webpack: Webpack
  rollup: Rollup
  parcel: Parcel
  esbuild: esbuild
  swc: SWC
  babel: Babel
  eslint: ESLint
  prettier: Prettier
  typescript: TypeScript
  jest: Jest
  vitest: Vitest
  cypress: Cypress
  playwright: Playwright
  testing-library: Testing Library
  storybook: Storybook
  chromatic: Chromatic
  lighthouse: Lighthouse
  pagespeed: PageSpeed
  core-web-vitals: Core Web Vitals
  lcp: LCP
  inp: INP
  cls: CLS
  fcp: FCP
  ttfb: TTFB
  fid: FID
  tbt: TBT
  cls: CLS
  si: SI
  ttci: TTCI
  dcl: DCL
  fmp: FMP
  vcp: VCP
  tti: TTI
  tti: TTI
  tbt: TBT
  cls: CLS
  si: SI
  ttci: TTCI
  dcl: DCL
  fmp: FMP
  vcp: VCP
