/**
 * @file packages/widgets/src/{{name}}/stories/{{name}}.stories.tsx
 * Generated by: turbo gen fsd-slice
 * Layer: widgets - Storybook stories
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import type { Meta, StoryObj } from '@storybook/react';
import { {{pascalCase name}}Widget } from '../{{name}}';
import type { {{pascalCase name}} } from '@x/entities/{{name}}';

const mockData: {{pascalCase name}} = {
  id: 'story-id',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  // Add any required fields for {{pascalCase name}} here
} as unknown as {{pascalCase name}};

const meta: Meta<typeof {{pascalCase name}}Widget> = {
  title: 'Widgets/{{pascalCase name}}',
  component: {{pascalCase name}}Widget,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof {{pascalCase name}}Widget>;

export const Default: Story = {
  args: {
    data: mockData,
  },
};

export const WithCustomData: Story = {
  args: {
    data: {
      ...mockData,
      id: 'custom-id',
    },
  },
};
