/**
 * @file packages/features/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: features - Use cases and business logic
 */

// Export all from the {{name}} feature module
export * from './{{name}}';

// Re-export commonly used items
export type { {{pascalCase name}}Service } from './{{name}}';
export { {{camelCase name}}Api } from './{{name}}';
