/**
 * @file packages/features/src/{{name}}/index.ts
 * @summary Feature module export file for {{name}} business logic and use cases.
 * @description Generated by FSD slice generator; exports feature services and API interfaces.
 * @security Template file; runtime security depends on implementation.
 * @adr docs/architecture/decisions/ADR-003-fsd-generators.md
 * @requirements FSD-001, FEATURE-TEMPLATE-001
 */
/**
 * @file packages/features/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: features - Use cases and business logic
 */

// Export all from the {{name}} feature module
export * from './{{name}}';

// Re-export commonly used items
export type { {{pascalCase name}}Service } from './{{name}}';
export { {{camelCase name}}Api } from './{{name}}';
