/**
 * @file packages/features/src/{{name}}/{{name}}.ts
 * Generated by: turbo gen fsd-slice
 * Layer: features - Use cases and business logic
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import type { Result } from '@repo/shared';
import type { {{pascalCase name}}Repository } from '@x/entities/{{name}}';
import { {{pascalCase name}}Service } from '@x/entities/{{name}}';

/**
 * {{description}} feature service
 */
export class {{pascalCase name}}Service {
  constructor(private entityService: {{pascalCase name}}Service) {}

  async create{{pascalCase name}}(data: any): Promise<Result<any, Error>> {
    // Add feature-specific business logic here
    return this.entityService.create{{pascalCase name}}(data);
  }

  async get{{pascalCase name}}(id: string): Promise<Result<any, Error>> {
    // Add feature-specific business logic here
    return this.entityService.get{{pascalCase name}}(id);
  }

  async update{{pascalCase name}}(id: string, data: any): Promise<Result<any, Error>> {
    // Add feature-specific business logic here
    return this.entityService.update{{pascalCase name}}(id, data);
  }

  async delete{{pascalCase name}}(id: string): Promise<Result<boolean, Error>> {
    // Add feature-specific business logic here
    return this.entityService.delete{{pascalCase name}}(id);
  }
}

/**
 * {{description}} API layer
 */
export const {{camelCase name}}Api = {
  async create(data: any) {
    const service = new {{pascalCase name}}Service(/* repository */);
    return service.create{{pascalCase name}}(data);
  },
  
  async get(id: string) {
    const service = new {{pascalCase name}}Service(/* repository */);
    return service.get{{pascalCase name}}(id);
  },
  
  async update(id: string, data: any) {
    const service = new {{pascalCase name}}Service(/* repository */);
    return service.update{{pascalCase name}}(id, data);
  },
  
  async delete(id: string) {
    const service = new {{pascalCase name}}Service(/* repository */);
    return service.delete{{pascalCase name}}(id);
  },
};
