packages:
  - 'packages/*'
  - 'packages/config/*'
  - 'packages/integrations/*'
  - 'packages/features/*'
  - 'packages/ai-platform/*'
  - 'packages/content-platform/*'
  - 'packages/marketing-ops/*'
  - 'packages/infrastructure/*'
  - 'clients/*'
  - 'apps/*'
  - 'tooling/*'

# [Task 0.5.1] Centralized version catalog for monorepo-wide consistency
catalog:
  next: '16.1.5'
  react: '19.0.0'
  react-dom: '19.0.0'
  typescript: '5.9.3'
  '@sentry/nextjs': '10.38.0'
  '@types/node': '^22.0.0'
  '@types/react': '^19.0.2'
  '@types/react-dom': '^19.0.2'
  '@types/jest': '^30.0.0'
  jest: '^30.2.0'
  zod: '^3.22.0'
  eslint: '^9.18.0'
  'radix-ui': '^1.0.0'
  'lucide-react': '^0.344.0'
  sonner: '^2.0.7'
