packages:
  - packages/*
  - packages/config/*
  - packages/integrations/*
  - packages/features/*
  - packages/infrastructure/*
  - clients/*
  - tooling/*

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: true
  unrs-resolver: true

blockExoticSubdeps: true

catalog:
  '@sentry/nextjs': 10.38.0
  '@testing-library/jest-dom': ^6.9.1
  '@types/jest': ^30.0.0
  '@types/node': ^22.19.11
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
  eslint: ^9.18.0
  jest: ^30.2.0
  jsdom: ^25.0.0
  lucide-react: ^0.344.0
  next: 16.1.5
  next-intl: ^3.25.0
  radix-ui: ^1.0.0
  react: 19.0.0
  react-dom: 19.0.0
  sonner: ^2.0.7
  typescript: 5.9.3
  vitest: ^3.2.4
  zod: ^3.25.76

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@sentry/cli'
