packages:
  - packages/*
  - packages/config/*
  - packages/integrations/*
  - packages/features/*
  - packages/ai-platform/*
  - packages/content-platform/*
  - packages/marketing-ops/*
  - packages/infrastructure/*
  - clients/*
  - tooling/*

# pnpm 10 supply chain security configuration
# Prevents supply chain attacks via malicious build scripts and exotic protocols
# See docs/architecture/security/supply-chain.md for full rationale and threat model
allowBuilds:
  # esbuild — JavaScript bundler used by Next.js and toolchain
  esbuild: true
  # sharp — native image processing; postinstall downloads prebuilt libvips bindings
  sharp: true
  # unrs-resolver — Rust-based module resolver used by ESLint / Rollup toolchain
  unrs-resolver: true
  # @sentry/cli — Sentry CLI binary download for source map uploads
  '@sentry/cli': true

# Block exotic protocols in transitive dependencies (git+ssh, tarball URLs, etc.)
# Prevents dependency confusion and typosquatting attacks
blockExoticSubdeps: true

# pnpm 10 supply chain security — only these packages may execute build scripts
# (install / postinstall / preinstall) during `pnpm install`. Any new dependency
# requiring a build script must be added here with justification reviewed in PR.
# See docs/architecture/security/supply-chain.md for full rationale and threat model.
onlyBuiltDependencies:
  # sharp — native image processing; postinstall downloads prebuilt libvips bindings.
  # Without this, Next.js image optimisation falls back to pure-JS (10× slower) or fails.
  - sharp
  # unrs-resolver — Rust-based module resolver used by ESLint / Rollup toolchain.
  # Postinstall (via napi-postinstall) selects the correct platform binary.
  # Without this, the package is non-functional and ESLint resolution breaks.
  - unrs-resolver
  # @sentry/cli — Sentry CLI binary download; postinstall selects platform-specific binary.
  # Required for source map uploads and release creation in CI/CD.
  - '@sentry/cli'

catalog:
  '@sentry/nextjs': 10.38.0
  '@types/jest': ^30.0.0
  '@types/node': ^22.0.0
  '@types/react': ^19.0.2
  '@types/react-dom': ^19.0.2
  eslint: ^9.18.0
  jest: ^30.2.0
  lucide-react: ^0.344.0
  next: 16.1.5
  next-intl: ^3.25.0
  radix-ui: ^1.0.0
  react: 19.0.0
  react-dom: 19.0.0
  sonner: ^2.0.7
  typescript: 5.9.3
  zod: ^3.25.76
