/**
 * @file packages/entities/src/{{name}}/index.ts
 * @summary Entity module export file for {{name}} domain object.
 * @description Generated by FSD slice generator; exports entity and repository types.
 * @security Template file; no runtime security implications.
 * @adr docs/architecture/decisions/ADR-003-fsd-generators.md
 * @requirements FSD-001, ENTITY-TEMPLATE-001
 */
/**
 * @file packages/entities/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: entities - Business logic and domain models
 */

// Export all from the {{name}} entity module
export * from './{{name}}';

// Re-export commonly used items
export type { {{pascalCase name}} } from './{{name}}';
export type { {{pascalCase name}}Repository } from './{{name}}';
