/**
 * @file packages/entities/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: entities - Business logic and domain models
 */

// Export all from the {{name}} entity module
export * from './{{name}}';

// Re-export commonly used items
export type { {{pascalCase name}} } from './{{name}}';
export type { {{pascalCase name}}Repository } from './{{name}}';
