/**
 * @file packages/entities/src/{{name}}/{{name}}.ts
 * Generated by: turbo gen fsd-slice
 * Layer: entities - Business logic and domain models
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import type { Result } from '@repo/shared';

/**
 * {{description}} domain entity
 */
export interface {{pascalCase name}} {
  id: string;
  // Add entity properties here
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Repository interface for {{name}} entities
 */
export interface {{pascalCase name}}Repository {
  create(data: Omit<{{pascalCase name}}, 'id' | 'createdAt' | 'updatedAt'>): Promise<Result<{{pascalCase name}}, Error>>;
  findById(id: string): Promise<Result<{{pascalCase name}} | null, Error>>;
  update(id: string, data: Partial<{{pascalCase name}}>): Promise<Result<{{pascalCase name}}, Error>>;
  delete(id: string): Promise<Result<boolean, Error>>;
  // Add custom methods here
}

/**
 * {{description}} business logic
 */
export class {{pascalCase name}}Service {
  constructor(private repository: {{pascalCase name}}Repository) {}

  async create{{pascalCase name}}(data: Omit<{{pascalCase name}}, 'id' | 'createdAt' | 'updatedAt'>): Promise<Result<{{pascalCase name}}, Error>> {
    // Add business logic here
    return this.repository.create(data);
  }

  async get{{pascalCase name}}(id: string): Promise<Result<{{pascalCase name}} | null, Error>> {
    // Add business logic here
    return this.repository.findById(id);
  }

  async update{{pascalCase name}}(id: string, data: Partial<{{pascalCase name}}>): Promise<Result<{{pascalCase name}}, Error>> {
    // Add business logic here
    return this.repository.update(id, data);
  }

  async delete{{pascalCase name}}(id: string): Promise<Result<boolean, Error>> {
    // Add business logic here
    return this.repository.delete(id);
  }
}
