/**
 * @file packages/widgets/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: widgets - UI components that use features
 */

// Export all from the {{name}} widget module
export * from './{{name}}';

// Re-export commonly used items
export { {{pascalCase name}}Widget } from './{{name}}';
