/**
 * @file packages/widgets/src/{{name}}/{{name}}.tsx
 * Generated by: turbo gen fsd-slice
 * Layer: widgets - UI components that use features
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

'use client';

import React from 'react';
import type { {{pascalCase name}}Service } from '@x/features/{{name}}';
import type { {{pascalCase name}} } from '@x/entities/{{name}}';

/**
 * {{description}} widget component
 */
export function {{pascalCase name}}Widget({ data }: { data: {{pascalCase name}} }) {
  const service = new {{pascalCase name}}Service(/* repository */);
  
  return (
    <div className="{{kebabCase name}}-widget">
      <h2>{{pascalCase name}} Widget</h2>
      {/* Add widget UI here */}
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  );
}
