name: Bug Report
description: Report a reproducible bug in apps, packages, or tooling
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail for reproducibility.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: A concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Include commands, routes, tenant context, and inputs.
      placeholder: |
        1. Run `pnpm dev`
        2. Open ...
        3. Click ...
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Affected scope
      description: List packages/apps/clients and relevant files.
      placeholder: packages/ui, clients/acme, docs/...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, pnpm version
      placeholder: Ubuntu 24.04, Node 22.13.0, pnpm 10.29.2
  - type: checkboxes
    id: checks
    attributes:
      label: Validation
      options:
        - label: I searched existing issues first.
          required: true
        - label: I can reproduce this issue on the latest main branch.
          required: true
