name: Security Finding
description: Track, triage, and remediate a security finding from automated scans or manual review.
title: '[SECURITY] <short finding title>'
labels:
  - security
  - triage
body:
  - type: input
    id: source_workflow
    attributes:
      label: Source workflow
      description: Workflow name and run URL where the finding was detected.
      placeholder: security-sast.yml - https://github.com/org/repo/actions/runs/123456
    validations:
      required: true

  - type: input
    id: affected_paths
    attributes:
      label: Affected paths/packages
      placeholder: packages/ui/src/button.tsx, clients/acme/app/api/route.ts
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (24h SLA)
        - High (72h SLA)
        - Medium (14d SLA)
        - Low (30d SLA)
    validations:
      required: true

  - type: input
    id: sla_due_date
    attributes:
      label: SLA due date (UTC)
      placeholder: 2026-03-01
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Finding details and evidence
      description: Include rule ID, CWE/OWASP mapping, reproduction details, and logs.
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: Remediation plan
      description: Steps, owner, and rollback/verification strategy.
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Verification checklist
      options:
        - label: A fix PR has been opened and linked in this issue.
        - label: Security workflow has been rerun and passed after fix.
        - label: Root cause and preventive action were documented.
