/**
 * @file packages/shared/src/{{name}}/__tests__/{{name}}.test.ts
 * Generated by: turbo gen fsd-slice
 * Layer: shared - Cross-cutting utilities and types
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import { describe, it, expect } from 'vitest';
import { create{{pascalCase name}}, validate{{pascalCase name}} } from '../{{name}}';
import type { {{pascalCase name}}Config } from '../{{name}}';

describe('create{{pascalCase name}}', () => {
  it('should return a config object when called with no arguments', () => {
    const config = create{{pascalCase name}}();

    expect(config).toBeDefined();
    expect(typeof config).toBe('object');
  });

  it('should merge provided overrides with defaults', () => {
    const overrides: Partial<{{pascalCase name}}Config> = {};
    const config = create{{pascalCase name}}(overrides);

    expect(config).toMatchObject(overrides);
  });
});

describe('validate{{pascalCase name}}', () => {
  it('should return true for a valid config', () => {
    const config = create{{pascalCase name}}();

    expect(validate{{pascalCase name}}(config)).toBe(true);
  });
});
