/**
 * @file packages/entities/src/{{name}}/__tests__/{{name}}.test.ts
 * Generated by: turbo gen fsd-slice
 * Layer: entities - Business logic and domain models
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import { describe, it, expect, vi } from 'vitest';
import { {{pascalCase name}}Service } from '../{{name}}';
import type { {{pascalCase name}}, {{pascalCase name}}Repository } from '../{{name}}';

const makeRepository = (overrides: Partial<{{pascalCase name}}Repository> = {}): {{pascalCase name}}Repository => ({
  create: vi.fn().mockResolvedValue({ ok: true, value: { id: '1' } as unknown as {{pascalCase name}} }),
  findById: vi.fn().mockResolvedValue({ ok: true, value: null }),
  update: vi.fn().mockResolvedValue({ ok: true, value: { id: '1' } as unknown as {{pascalCase name}} }),
  delete: vi.fn().mockResolvedValue({ ok: true, value: true }),
  ...overrides,
});

describe('{{pascalCase name}}Service', () => {
  describe('create{{pascalCase name}}', () => {
    it('should call repository.create with the provided data', async () => {
      const repository = makeRepository();
      const service = new {{pascalCase name}}Service(repository);
      const createData = { /* add required fields */ } as Omit<{{pascalCase name}}, 'id' | 'createdAt' | 'updatedAt'>;

      await service.create{{pascalCase name}}(createData);

      expect(repository.create).toHaveBeenCalledWith(createData);
    });
  });

  describe('get{{pascalCase name}}', () => {
    it('should call repository.findById with the provided id', async () => {
      const repository = makeRepository();
      const service = new {{pascalCase name}}Service(repository);

      await service.get{{pascalCase name}}('test-id');

      expect(repository.findById).toHaveBeenCalledWith('test-id');
    });
  });

  describe('update{{pascalCase name}}', () => {
    it('should call repository.update with id and data', async () => {
      const repository = makeRepository();
      const service = new {{pascalCase name}}Service(repository);
      const updates: Partial<{{pascalCase name}}> = { updatedAt: new Date() };

      await service.update{{pascalCase name}}('test-id', updates);

      expect(repository.update).toHaveBeenCalledWith('test-id', updates);
    });
  });

  describe('delete{{pascalCase name}}', () => {
    it('should call repository.delete with the provided id', async () => {
      const repository = makeRepository();
      const service = new {{pascalCase name}}Service(repository);

      await service.delete{{pascalCase name}}('test-id');

      expect(repository.delete).toHaveBeenCalledWith('test-id');
    });
  });
});
