/**
 * @file packages/shared/src/{{name}}/index.ts
 * Generated by: turbo gen fsd-slice
 * Layer: shared - Cross-cutting utilities and types
 */

// Export all from the {{name}} shared module
export * from './{{name}}';

// Re-export commonly used items
export type { {{pascalCase name}} } from './{{name}}';
