/**
 * @file packages/shared/src/{{name}}/{{name}}.ts
 * Generated by: turbo gen fsd-slice
 * Layer: shared - Cross-cutting utilities and types
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

/**
 * {{description}} shared utilities and types
 */

// Types
export interface {{pascalCase name}}Config {
  // Add configuration properties here
}

// Constants
export const {{constantCase name}}_DEFAULTS = {
  // Add default values here
} as const;

// Utility functions
export function create{{pascalCase name}}(config: Partial<{{pascalCase name}}Config> = {}): {{pascalCase name}}Config {
  return {
    // Merge with defaults
    ...{{constantCase name}}_DEFAULTS,
    ...config,
  };
}

// Helper functions
export function validate{{pascalCase name}}(config: {{pascalCase name}}Config): boolean {
  // Add validation logic here
  return true;
}
