/**
 * @file packages/features/src/{{name}}/__tests__/{{name}}.test.ts
 * Generated by: turbo gen fsd-slice
 * Layer: features - Use cases and business logic
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import { describe, it, expect, vi } from 'vitest';
import { {{pascalCase name}}Service } from '../{{name}}';

describe('{{pascalCase name}}Service (feature layer)', () => {
  describe('create{{pascalCase name}}', () => {
    it('should delegate to the entity service', async () => {
      const entityService = {
        create{{pascalCase name}}: vi.fn().mockResolvedValue({ ok: true, value: {} }),
        get{{pascalCase name}}: vi.fn(),
        update{{pascalCase name}}: vi.fn(),
        delete{{pascalCase name}}: vi.fn(),
      } as unknown as InstanceType<typeof {{pascalCase name}}Service>;

      const service = new {{pascalCase name}}Service(entityService);
      const data = {};

      // @ts-expect-error – entityService is a mock; cast is intentional
      await service.create{{pascalCase name}}(data);

      expect(entityService.create{{pascalCase name}}).toHaveBeenCalledWith(data);
    });
  });

  describe('get{{pascalCase name}}', () => {
    it('should delegate to the entity service', async () => {
      const entityService = {
        create{{pascalCase name}}: vi.fn(),
        get{{pascalCase name}}: vi.fn().mockResolvedValue({ ok: true, value: null }),
        update{{pascalCase name}}: vi.fn(),
        delete{{pascalCase name}}: vi.fn(),
      } as unknown as InstanceType<typeof {{pascalCase name}}Service>;

      const service = new {{pascalCase name}}Service(entityService);

      // @ts-expect-error – entityService is a mock; cast is intentional
      await service.get{{pascalCase name}}('test-id');

      expect(entityService.get{{pascalCase name}}).toHaveBeenCalledWith('test-id');
    });
  });
});
