/**
 * @file packages/widgets/src/{{name}}/__tests__/{{name}}.test.tsx
 * Generated by: turbo gen fsd-slice
 * Layer: widgets - UI components that use features
{{#if description}}
 * Description: {{description}}
{{/if}}
 */

import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { {{pascalCase name}}Widget } from '../{{name}}';
import type { {{pascalCase name}} } from '@x/entities/{{name}}';

const mockData: {{pascalCase name}} = {
  id: 'test-id',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  // Add any required fields for {{pascalCase name}} here
} as unknown as {{pascalCase name}};

describe('{{pascalCase name}}Widget', () => {
  it('should render without crashing', () => {
    render(<{{pascalCase name}}Widget data={mockData} />);

    expect(screen.getByText(/{{pascalCase name}} Widget/i)).toBeInTheDocument();
  });

  it('should display the entity data', () => {
    render(<{{pascalCase name}}Widget data={mockData} />);

    expect(screen.getByText(/test-id/i)).toBeInTheDocument();
  });
});
