// File: packages/infra/accessibility/aria.ts  [TRACE:FILE=packages.infra.accessibility.aria]
// Purpose: ARIA attribute utilities for building accessible components.
//          Provides typed helpers for generating correct ARIA attribute objects
//          that can be spread onto JSX elements.
//
// System role: Client-safe ARIA utilities (no server-only imports).
// Assumptions: DOM is available; use in React components or plain DOM code.
//
// Exports: generateAriaId, labelledBy, describedBy, ariaExpanded, ariaSelected,
//          ariaPressed, ariaChecked, ariaHidden, ariaLive, ariaRole, mergeAriaProps
//
// Invariants:
// - No side effects — all functions are pure
// - All returned attribute objects are valid WAI-ARIA 1.2 attribute sets
// - IDs generated by generateAriaId are stable within a prefix+suffix pair
//
// Status: @public
// Features:
// - [FEAT:ACCESSIBILITY] WAI-ARIA attribute generation

let _idCounter = 0;

/**
 * Generate a unique, stable DOM ID string with an optional prefix.
 * Intended for linking aria-labelledby / aria-describedby to their targets.
 *
 * @example
 * const titleId = generateAriaId('dialog-title');  // "aria-dialog-title-1"
 */
export function generateAriaId(prefix = 'aria'): string {
  _idCounter += 1;
  return `${prefix}-${_idCounter}`;
}

/**
 * Build an `aria-labelledby` attribute object from one or more element IDs.
 * Multiple IDs are joined with a space (per ARIA spec).
 *
 * @example
 * <div {...labelledBy('title-id', 'subtitle-id')}>…</div>
 */
export function labelledBy(...ids: string[]): { 'aria-labelledby': string } {
  return { 'aria-labelledby': ids.filter(Boolean).join(' ') };
}

/**
 * Build an `aria-describedby` attribute object from one or more element IDs.
 *
 * @example
 * <input {...describedBy('hint-id', 'error-id')} />
 */
export function describedBy(...ids: string[]): { 'aria-describedby': string } {
  return { 'aria-describedby': ids.filter(Boolean).join(' ') };
}

/**
 * Build an `aria-expanded` attribute object.
 * Typically used on trigger elements (buttons, disclosure toggles).
 */
export function ariaExpanded(expanded: boolean): { 'aria-expanded': boolean } {
  return { 'aria-expanded': expanded };
}

/**
 * Build an `aria-selected` attribute object.
 * Used in tablist/listbox widgets.
 */
export function ariaSelected(
  selected: boolean
): { 'aria-selected': boolean } {
  return { 'aria-selected': selected };
}

/**
 * Build an `aria-pressed` attribute object for toggle buttons.
 */
export function ariaPressed(
  pressed: boolean | 'mixed'
): { 'aria-pressed': boolean | 'mixed' } {
  return { 'aria-pressed': pressed };
}

/**
 * Build an `aria-checked` attribute object.
 * Accepts `true`, `false`, or `'mixed'` for tri-state checkboxes.
 */
export function ariaChecked(
  checked: boolean | 'mixed'
): { 'aria-checked': boolean | 'mixed' } {
  return { 'aria-checked': checked };
}

/**
 * Build an `aria-hidden` attribute object.
 * Use `true` to remove decorative elements from the accessibility tree.
 */
export function ariaHidden(hidden: boolean): { 'aria-hidden': true | undefined } {
  return { 'aria-hidden': hidden ? true : undefined };
}

/**
 * Build an `aria-live` + `aria-atomic` attribute object for live regions.
 *
 * @param politeness - 'polite' for status messages, 'assertive' for errors
 * @param atomic     - when true, AT re-reads the entire region on change
 */
export function ariaLive(
  politeness: 'polite' | 'assertive' | 'off' = 'polite',
  atomic = true
): { 'aria-live': 'polite' | 'assertive' | 'off'; 'aria-atomic': boolean } {
  return { 'aria-live': politeness, 'aria-atomic': atomic };
}

/**
 * Build a `role` attribute object.
 * Narrows to common WAI-ARIA landmark and widget roles.
 */
export function ariaRole(
  role:
    | 'alert'
    | 'alertdialog'
    | 'banner'
    | 'button'
    | 'checkbox'
    | 'complementary'
    | 'contentinfo'
    | 'dialog'
    | 'feed'
    | 'form'
    | 'grid'
    | 'gridcell'
    | 'group'
    | 'img'
    | 'link'
    | 'list'
    | 'listbox'
    | 'listitem'
    | 'log'
    | 'main'
    | 'marquee'
    | 'menu'
    | 'menubar'
    | 'menuitem'
    | 'menuitemcheckbox'
    | 'menuitemradio'
    | 'navigation'
    | 'none'
    | 'option'
    | 'presentation'
    | 'progressbar'
    | 'radio'
    | 'radiogroup'
    | 'region'
    | 'row'
    | 'rowgroup'
    | 'rowheader'
    | 'scrollbar'
    | 'search'
    | 'searchbox'
    | 'separator'
    | 'slider'
    | 'spinbutton'
    | 'status'
    | 'switch'
    | 'tab'
    | 'table'
    | 'tablist'
    | 'tabpanel'
    | 'term'
    | 'textbox'
    | 'timer'
    | 'toolbar'
    | 'tooltip'
    | 'tree'
    | 'treegrid'
    | 'treeitem'
): { role: string } {
  return { role };
}

/**
 * Merge multiple ARIA attribute objects into one, later objects win.
 * Useful for composing aria helpers.
 *
 * @example
 * const attrs = mergeAriaProps(labelledBy('id'), ariaExpanded(isOpen));
 */
export function mergeAriaProps(
  ...attrSets: Array<Record<string, unknown>>
): Record<string, unknown> {
  return Object.assign({}, ...attrSets);
}
